### ISSUE TITLE
环境变量梳理

### ISSUE THREAD

**Issue by monsterboom** [LISTENAI/lisa-plugin-zephyr#51]
“沙盒”环境实际与系统环境进行了混搭，是否可以进行“沙盒”环境存在的相关包，在系统环境进行过滤。
比如：python是“沙盒”环境中需要用到的在"沙盒"中存在于“venv\Scripts”，然后过滤掉系统中，带有“Python”的环境变量。

**Comment by xingrz** [comment]
> 然后过滤掉系统中，带有“Python”的环境变量。

很难做到这种有条件的排除的。只能完全不传入所有系统的变量（完全不让使用沙盒外的工具）。

**Comment by monsterboom** [comment]
已经在Lisa层，将系统环境变量进行了过滤，到zephyr插件用的，均是沙盒内环境。
